### ISSUE TITLE
TZ Timezone is not taken from the host system

### ISSUE THREAD

**Issue by I2e4per** [thkukuk/fritzbox-monitoring#2]
Hello Thorsten,

first of all i would mention that I am very happy with your container and that I am using it quit for a while.I Appreciate your efforts.
An I want to point out, that this issue isn't really an issue from my point of view. It is more a nice to have related issue.

I am running your container on an Sync DS on Portainer. And for some reason, it does not take the actual Timezone from the Syno. Instead it uses the default.

So i tinkered a little around and I managed to set it right for my case with followed commands:

rm -rf /etc/localtime
ln -s /usr/share/zoneinfo/Europe/Berlin /etc/localtime

The big disadvantage of this is, that it has of course to be redone after every powercycle / reboot and so on.

Now I am wondering how you manage this ? Or aren't you facing this maybe because you are using another platform ?

Could it be a solution to add an extra TZ Environment Variable to pass the correct timezone and have it configurable ?
In this case i.e. "TZ=Europe/Berlin"

Thank you!

**Comment by thkukuk** [comment]
Do you mean the mrtg based container? This has the TZ Environment Variable, it was just missing in the README.

**Comment by thkukuk** [comment]
Works for me

**Comment by I2e4per** [comment]
Works for me either.

Great job. Thank you!
