### ISSUE TITLE
Zoom not working

### ISSUE THREAD

**Issue by subascha** [thkukuk/fritzbox-monitoring#3]
Hi,

just installed your munin docker container but having trouble zooming in.

`fritzbox_traffic_py-pinpoint=1642631690,1642633445.png:1 Failed to load resource: the server responded with a status of 404 (Not Found)`

Everything else is working fine.

Best regards from Germany
Sascha

**Comment by thkukuk** [comment]
CGI scripts were not enabled/started, fixed now.

**Comment by subascha** [comment]
> CGI scripts were not enabled/started, fixed now.

Thank you!
